### ISSUE TITLE
Diagramme de classe

### ISSUE THREAD

**Issue by tudoriordan1** [IliassNazih/H23-Equipe-7#10]

**Comment by tudoriordan1** [comment]
https://lucid.app/lucidchart/5ba5adb0-55ec-49f1-8eee-3b1a7ae2b7ec/edit?invitationId=inv_59d4a0b5-8a4e-43f7-aaf1-df72223f6dfa

**Comment by hugogv12** [comment]
[Diagramme classes.pdf](https://github.com/IliassNazih/H23-Equipe-7/files/10739980/Diagramme.classes.pdf)
