### ISSUE TITLE
Diagrammes de vues

### ISSUE THREAD

**Issue by tudoriordan1** [IliassNazih/H23-Equipe-7#7]

**Comment by hugogv12** [comment]
![Image](https://user-images.githubusercontent.com/123586556/220229644-ac9ff058-2024-40f9-a48d-f5e8ca1b3c3e.png)

Entrer dans l'appli

**Comment by hugogv12** [comment]
![Image](https://user-images.githubusercontent.com/123586556/220231544-4b49efd5-3561-4196-a0a5-186a14d2d0f7.png)


map

**Comment by hugogv12** [comment]
https://lucid.app/publicSegments/view/b415e342-71f9-43c3-ac33-a31c2d5aa011 pour quand on appuie sur crédit de compte dans profil

**Comment by hugogv12** [comment]
[https://lucid.app/documents/view/41ee7720-b798-400e-a554-5e5ed1c6f5f3](url) pour quand on appuie sur infos de compte

**Comment by hugogv12** [comment]
Historique de l'activite


![Image](https://user-images.githubusercontent.com/123586556/220234430-e10d0c0c-97a9-4005-bb9f-26b02e1e95c4.png)

**Comment by hugogv12** [comment]
Messagerie
[Messagerie.pdf](https://github.com/IliassNazih/H23-Equipe-7/files/10728441/Messagerie.pdf)
